CREATE TABLE FEATURES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR (255) not null,
  DESCRIPTION VARCHAR(255) not null,
  AUTHOR VARCHAR(255) not null,
  IMAGE_URL VARCHAR(255) not null,
  PRIMARY KEY (ID)
);

