
CREATE TABLE FEATURES (
	ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
	NAME varchar(255) not null,
	DESCRIPTION varchar(255) not null,
	AUTHOR varchar(255) not null,
	IMAGE_URL varchar(255) not null
);
