CREATE TABLE TASKS(
    TASK_ID BIGINT NOT NULL AUTO_INCREMENT,
    TASK_NAME VARCHAR(255) not null,
    TASK_DESCRIPTION VARCHAR(255) not null,
    ESTIMATE_TIME int not null,
    ESTIMATE_PRICE int not null,
    PRIMARY KEY (TASK_ID)
 );



