CREATE TABLE USERS (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(255) NOT NULL,
    USER_JOB VARCHAR(255),
    USER_EARNINGS FLOAT,
    USER_SAVINGS FLOAT,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE EXPENSE_TYPES (
    EXPENSE_TYPE_ID BIGINT NOT NULL AUTO_INCREMENT,
    EXPENSE_TYPE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (EXPENSE_TYPE_ID)
);

CREATE TABLE SAVINGS_GOAL(
    SAVINGS_GOAL_ID BIGINT NOT NULL AUTO_INCREMENT,
    SAVINGS_GOAL_NAME VARCHAR(255) NOT NULL,
    SAVINGS_GOAL_VALUE FLOAT NOT NULL,
    SAVINGS_GOAL_MONEY_TO_ACCOMPLISH FLOAT,
    SAVINGS_GOAL_ACCOMPLISHMENT BIT DEFAULT 0,
    SAVINGS_GOAL_USER_ID BIGINT NOT NULL,
    PRIMARY KEY(SAVINGS_GOAL_ID),
    FOREIGN KEY(SAVINGS_GOAL_USER_ID) REFERENCES USERS(USER_ID)

);

CREATE TABLE EXPENSES (
    EXPENSE_ID BIGINT NOT NULL AUTO_INCREMENT,
    EXPENSE_NAME VARCHAR(255) NOT NULL,
    EXPENSE_DESCRIPTION VARCHAR(255),
    EXPENSE_VALUE FLOAT NOT NULL,
    EXPENSE_DATE DATE NOT NULL,
    EXPENSE_USER_ID BIGINT NOT NULL,
    EXPENSE_TYPE_ID BIGINT NOT NULL,
    PRIMARY KEY (EXPENSE_ID),
    FOREIGN KEY (EXPENSE_USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (EXPENSE_TYPE_ID) REFERENCES EXPENSE_TYPES(EXPENSE_TYPE_ID)
);

INSERT INTO FEATURES(NAME, DESCRIPTION, AUTHOR, IMAGE_URL)
VALUES('FinancialCalculator', 'You can save your daily expenses, then check them month by month, update your savings and finally fulfill your savings goals!','Lukasz','http://www.editorstop.com/wp-content/uploads/2016/01/financial-calculator.jpg');